### PR TITLE
List more objects from bucket.

### PR DESCRIPTION
**Pull request by petrbroz**
- Changed the page size when listing objects in bucket to 100
- Added code comment explaining that additional `getObjects` calls might be needed

### CODE REVIEW

**Comment by augustogoncalves** [comment]
it seems the getBuckets is returning only 64, shouldn't be 100 too? 

I'll adjust the .NET & .NET Core branches

**Comment by petrbroz** [comment]
Sure, let me update the bucket listing code in the same way.

**Comment by stevestan19** [comment]
My I know how to create delete bucket button in oss.js & Forgetree.js ?

**Comment by augustogoncalves** [comment]
> My I know how to create delete bucket button in oss.js & Forgetree.js ? Im use Nodejs..

This sample was intentionally left simple. You can change the Forgetree.js file to add a new right-click menu item to call `DELETE /buckets/:bucketKey:` endpoint

**Pull request merged**
