### PR TITLE
migrated to sdk 1.0.2

### PR DESCRIPTION
**Pull request by xiaodongliang**
migrated to sdk 1.0.2 and fixed issue of importing viewer js

### CODE REVIEW

**Comment by augustogoncalves** [comment]
@xiaodongliang do we need to change the tutorial? https://github.com/Developer-Autodesk/forge.learning ?

**Comment by augustogoncalves** [comment]
and can you remove the changes you did on `index.html`? it should come from the master (ui) branch (I'll fix it later and push to all other branches)

**Comment by xiaodongliang** [comment]
@augustogoncalves ,yes, we need to change the tutorial as well. I remember I had PR for tutorial.. 
about 'removing changes on index.html', could you guide how to do? I have no experience to veto partial change of a PR...or I submit a new PR?

**Comment by augustogoncalves** [comment]
@xiaodongliang can you please remove the index.html from your PR? the html/js/css files should come from the master branch (already updated to v7). Thanks!

**Comment by xiaodongliang** [comment]
@augustogoncalves , apology for the delay response. I just noticed your message. It looks you have migrated html/js for all branches. Do I still need to do something on the repo of JAVA?

**Comment by augustogoncalves** [comment]
@xiaodongliang I see you did some changes to the JAVA specific files... if that still needed, then yes, please adjust on this PR so I can merge it.

**Comment by xiaodongliang** [comment]
@augustogoncalves , I see. I did had two commits...let me check and keep the update of pom.xml only.

**Comment by xiaodongliang** [comment]
@augustogoncalves , it might be a stupid way, while I synced upstream, updated pom.xml only and created a new PR. Please check if it is fine. 
https://github.com/Autodesk-Forge/learn.forge.viewmodels/pull/27

**Pull request closed without merging**
