### PR TITLE
Add bucketKey sanitization

### PR DESCRIPTION
**Pull request by deepalics0044**

### CODE REVIEW

**Comment by petrbroz** [comment]
I'm not sure if that code is correct. It sounds like it actually throws an alert **when the bucket name is valid**.

Shouldn't it be something like this instead?

```js
const regex = /^[\-_.a-z0-9]{3,128}$/g;
if (!bucketKey.match(regex)) {
    alert('Invalid bucket name!');
    return;
}
```

**Comment by petrbroz** [comment]
Closing in favor of PR #53.

**Comment by deepalics0044** [comment]
There's a '!' infront of the bucketKey.match(regex) which makes the code right

**Comment by deepalics0044** [comment]
I will test it again though :)

**Comment by deepalics0044** [comment]
pattern [^-_\.a-z0-9] match characters that are not listed in the range .

So condition should be if (reg.test(bucketKey))

var reg = new RegExp(/[^-_\.a-z0-9]/g);

if (reg.test(bucketKey)) {
 alert('Wrong  Bucketkey format!');
return;
}

**Comment by petrbroz** [comment]
Hi Deepali, I'm not sure I understand. Is the new code broken?

The regular expression I'm using is `/^[\-_.a-z0-9]{3,128}$/g;`. The `^` symbol is before the `[]` group, not inside, and it's meant to represent the "beginning of string".

**Pull request closed without merging**
