### PR TITLE
add bucketKey sanitization, package updates

### PR DESCRIPTION
**Pull request by tongwing**
I ran into an issue with bucket key containing upper case characters. This is a fix for bucket key with invalid characters.
Possibly address issue #37?

### CODE REVIEW

**Comment by augustogoncalves** [comment]
thank you @tongwing ! for the context of this tutorial (multiple backend languages), it may fit better on the client-side, where it can give feedback to the user.

**Comment by tongwing** [comment]
I see. In that case it seems like the changes should be made in ForgeTree.js. But that file is located in different places in the different branches. How can I help?

**Comment by augustogoncalves** [comment]
@tongwing we'll review the sample and add the check on the client, thanks for the suggestion.

**Comment by petrbroz** [comment]
Agree with @augustogoncalves. Checking the bucket name would make more sense on the client, and there's a pull request that's already addressing that: https://github.com/Autodesk-Forge/learn.forge.viewmodels/pull/46.

Feel free to update this PR so that it only updates the .gitignore file and the dependency versions, and we will merge it in.

**Comment by petrbroz** [comment]
Btw. the bucket validation has been addressed in #53.

**Comment by petrbroz** [comment]
Dependencies and gitignore updated n #55. Closing this one.

**Pull request closed without merging**
